=== RomZesM/SOAP_WebService_testTask/src/main/resources/xml/country_test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="root" type="rootType"/>

   <xs:complexType name="rootType">

        <xs:sequence>
            <xs:element type="countryType" name="country" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="countryType">

        <xs:sequence>
            <xs:element name="name" type="xs:string"/> <!--simple-type STRING, INT etc-->
            <xs:element name="capital" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="visa_cost" type="visa_costType"/>  <!--complex-Type - -like new obj with attr-->
        </xs:sequence>

        <xs:attribute type="xs:string" name="c_code" use="required"/>

    </xs:complexType>

    <xs:complexType name="visa_costType">   <!--for visa cost, if we want to add atribute-->

        <xs:simpleContent>
            <xs:extension base="xs:int">
                <xs:attribute type="xs:string" name="currency" use="required"/>
            </xs:extension>
        </xs:simpleContent>



    </xs:complexType>
    
</xs:schema>

=== RomZesM/SOAP_WebService_testTask/src/main/resources/xml/country.xml
<?xml version="1.0" encoding="utf-8"?>


<root xmlns:xs ="http://www.w3.org/2001/XMLSchema-instance"
        xs:noNamespaceSchemaLocation = "country_test.xsd">

    <country c_code = "de">
        <name>Germany</name>
        <capital>Berlin</capital>
        <description>Germany is awsome</description>
        <visa_cost currency="usd">777</visa_cost>
    </country>

    <country c_code = "fra">
        <name>France</name>
        <capital>Paris</capital>
        <description>I love wine!</description>
        <visa_cost currency="usd">777</visa_cost>
    </country>

    <country c_code = "gb">
        <name>Great Britain</name>
        <capital>London</capital>
        <description>London is a capital of GB</description>
        <visa_cost currency="usd">777</visa_cost>
    </country>

    <country c_code = "hng">
        <name>Britain</name>
        <capital>ondon</capital>
        <description>ondon is a capital of GB</description>
        <visa_cost currency="usd">777</visa_cost>
    </country>

</root>
